#!/usr/bin/python
import os

smooth = 100.0

# os.environ['CSCRATCH'] + '/trash/ensemble/' 
outdir = '/global/homes/m/mjwilson/sandbox/desimodel/trunk/data/tsnr/'

# Order of runtime. 
for tracer in ['bgs', 'lrg', 'qso', 'elg']:
    cmd = 'python desispec/scripts/tsnr_ensemble.py --nmodel 1000 --tracer {} --outdir {} --smooth {} --Nz'.format(tracer, outdir, smooth)

    os.system(cmd)
