#!/usr/bin/python
import os

smooth = 10.0
outdir = os.environ['CSCRATCH'] + '/trash/ensemble/'

# Order of time. 
for tracer in ['bgs', 'lrg', 'qso', 'elg']:
    cmd = 'python desispec/scripts/tsnr_ensemble.py --nmodel 1000 --tracer {} --outdir {} --smooth {} --Nz'.format(tracer, outdir, smooth)

    os.system(cmd)
